[package]
name = "lovpn-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "lovpn"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde_json.workspace = true
lovpn-config = { path = "../lovpn-config", version = "=0.1.0-dev.1" }
lovpn-keys = { path = "../lovpn-keys", version = "=0.1.0-dev.1" }
lovpn-firewall = { path = "../lovpn-firewall", version = "=0.1.0-dev.1" }

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
