[package]
name = "lovpn-firewall"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ipnet.workspace = true
lovpn-config = { path = "../lovpn-config", version = "=0.1.0-dev.1" }

[lints]
workspace = true

[dev-dependencies]
proptest.workspace = true
