"""End-to-end client gate: real client broker/engine and WireGuard in a sandbox.

Run only via ``scripts/test-networking.sh``.  The caller supplies the host network
namespace only so this test can prove it is not running on the host; the test itself
runs in the caller's disposable user+network+pid namespace.  A child network namespace
holds the client daemon and its veth uplink, while the caller's namespace holds the
server and its veth to the upstream echo service.

This gate deliberately uses the public CLI for offline enrollment and for every client
operation.  The private key is generated by ``lovpn identity generate`` and is only
ever passed by path to the CLI; it is never read or printed by this test.
"""

import json
import os
import shutil
import signal
import subprocess
import sys
import tempfile
import time

from server_e2e import ECHO, Namespace, probe, probe_within, require, run

ECHO6 = ("import socket;s=socket.socket(socket.AF_INET6,socket.SOCK_DGRAM);"
         "s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1);"
         "s.bind(('2001:db8:1::1',9997))\nwhile True:\n"
         " d,a=s.recvfrom(64);s.sendto(a[0].encode(),a)")
TCP_ECHO = ("import socket;s=socket.socket();s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1);"
            "s.bind(('192.0.2.1',9998));s.listen(4)\n"
            "while True:\n c,a=s.accept();\n"
            " while True:\n  d=c.recv(64)\n  if not d: break\n  c.sendall(d)\n c.close()")
PROBE6 = (
    "import socket,sys\n"
    "s=socket.socket(socket.AF_INET6,socket.SOCK_DGRAM)\n"
    "s.settimeout(1)\n"
    "try:\n"
    " s.sendto(b'x',(sys.argv[1],9997))\n"
    "except OSError:\n"
    " print('timeout')\n"
    " raise SystemExit(0)\n"
    "try:\n"
    " print(s.recv(64).decode())\n"
    "except Exception:\n"
    " print('timeout')\n"
)
BOUND_PROBE = (
    "import socket,sys\n"
    "s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)\n"
    "try:\n"
    " s.setsockopt(socket.SOL_SOCKET,socket.SO_BINDTODEVICE,sys.argv[2].encode()+b'\\0')\n"
    "except OSError:\n"
    " print('bind-denied')\n"
    " raise SystemExit(0)\n"
    "s.settimeout(1)\n"
    "try:\n"
    " s.sendto(b'x',(sys.argv[1],9999))\n"
    "except OSError:\n"
    " print('blocked')\n"
    " raise SystemExit(0)\n"
    "try:\n"
    " print(s.recv(64).decode())\n"
    "except Exception:\n"
    " print('timeout')\n"
)


class Lab:
    def __init__(self, host_netns, server_bin, client_bin, clientd_bin):
        self.host_netns = host_netns
        self.server_bin = os.path.abspath(server_bin)
        self.client_bin = os.path.abspath(client_bin)
        self.clientd_bin = os.path.abspath(clientd_bin)
        self.root = tempfile.mkdtemp(prefix="lovpn-client-e2e-")
        os.chmod(self.root, 0o700)
        self.server_state = os.path.join(self.root, "server-state")
        self.server_socket = os.path.join(self.root, "server.sock")
        self.server_broker_dir = os.path.join(self.root, "server-broker")
        os.mkdir(self.server_broker_dir, 0o700)
        self.client_state = os.path.join(self.root, "client-state")
        self.client_socket = os.path.join(self.root, "client.sock")
        self.namespaces = []
        self.helpers = []
        self.server_broker = None
        self.client_broker = None
        self.client_namespace = None

    def server(self, *args, check=True):
        return run(
            self.server_bin,
            "--state-dir",
            self.server_state,
            "--socket",
            self.server_socket,
            *args,
            check=check,
        )

    def client(self, *args, check=True):
        if self.client_namespace is None:
            raise RuntimeError("client namespace is not ready")
        return run(
            "nsenter",
            "-t",
            str(self.client_namespace.process.pid),
            "-n",
            "--",
            self.client_bin,
            "--socket",
            self.client_socket,
            *args,
            check=check,
        )

    def client_json(self, *args, check=True):
        result = self.client("--json", *args, check=check)
        if result.returncode != 0:
            return result, None
        return result, json.loads(result.stdout)

    def new_namespace(self):
        namespace = Namespace(self.host_netns)
        self.namespaces.append(namespace)
        return namespace

    def start_server_broker(self):
        self.server_broker = subprocess.Popen(
            [
                self.server_bin,
                "--state-dir",
                self.server_state,
                "--socket",
                self.server_socket,
                "broker",
                "--owner-uid",
                "0",
                "--broker-dir",
                self.server_broker_dir,
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        wait_for(self.server_ready, "server broker")

    def server_ready(self):
        result = self.server("status", "--live", "--json", check=False)
        return os.path.exists(self.server_socket) and result.returncode == 0

    def start_client_broker(self):
        if self.client_namespace is None:
            raise RuntimeError("client namespace is not ready")
        self.client_broker = subprocess.Popen(
            [
                "nsenter",
                "-t",
                str(self.client_namespace.process.pid),
                "-n",
                "--",
                self.clientd_bin,
                "--state-dir",
                self.client_state,
                "--socket",
                self.client_socket,
                "--owner-uid",
                "0",
                "--dns-backend",
                "unmanaged",
                "--monitor-interval-ms",
                "1000",
                "--handshake-wait-secs",
                "10",
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        wait_for(self.client_ready, "client broker")

    def client_ready(self):
        result, data = self.client_json("status", check=False)
        return result.returncode == 0 and data is not None and data.get("service") == "running"

    def stop_client_broker(self, force=False):
        if self.client_broker is not None:
            if self.client_broker.poll() is None:
                (self.client_broker.kill if force else self.client_broker.terminate)()
            self.client_broker.wait(timeout=5)
            self.client_broker = None

    def stop_server_broker(self):
        if self.server_broker is not None:
            if self.server_broker.poll() is None:
                self.server_broker.terminate()
            self.server_broker.wait(timeout=5)
            self.server_broker = None

    def close(self):
        self.stop_client_broker(force=True)
        self.stop_server_broker()
        for helper in self.helpers:
            if helper.poll() is None:
                helper.terminate()
            try:
                helper.wait(timeout=2)
            except subprocess.TimeoutExpired:
                helper.kill()
                helper.wait()
        for namespace in self.namespaces:
            namespace.close()
        shutil.rmtree(self.root, ignore_errors=True)


def wait_for(predicate, description, seconds=15):
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        if predicate():
            return
        time.sleep(0.1)
    raise AssertionError(f"{description} did not become ready")


def probe6(namespace, destination, attempts=3):
    for _ in range(attempts):
        answer = namespace.run("python3", "-c", PROBE6, destination).stdout.strip()
        if answer != "timeout":
            return answer
    return "timeout"


def bound_probe(namespace, destination, interface, attempts=3):
    for _ in range(attempts):
        answer = namespace.run(
            "python3", "-c", BOUND_PROBE, destination, interface
        ).stdout.strip()
        if answer != "timeout":
            return answer
    return "timeout"


LEAK_SENDER = (
    "import socket,sys\n"
    "for fam,kind,port in [(socket.AF_INET,socket.SOCK_DGRAM,53),(socket.AF_INET,socket.SOCK_STREAM,53),"
    "(socket.AF_INET,socket.SOCK_STREAM,853),(socket.AF_INET,socket.SOCK_DGRAM,443),"
    "(socket.AF_INET,socket.SOCK_DGRAM,5353),(socket.AF_INET,socket.SOCK_DGRAM,137)]:\n"
    " for dest in sys.argv[1:]:\n"
    "  s=socket.socket(fam,kind);s.settimeout(.3)\n"
    "  try:\n"
    "   if kind==socket.SOCK_DGRAM: s.sendto(b'leak-probe',(dest,port))\n"
    "   else: s.connect((dest,port))\n"
    "  except OSError: pass\n"
    "  s.close()\n"
    "import subprocess\n"
    "for dest in sys.argv[1:]: subprocess.run(['ping','-c','1','-W','1',dest],capture_output=True)\n"
)
SNIFFER = (
    "import socket,struct,sys,time\n"
    "socks=[]\n"
    "for n in sys.argv[2:]:\n"
    " s=socket.socket(socket.AF_PACKET,socket.SOCK_RAW,socket.htons(3));s.bind((n,0));s.settimeout(.2);socks.append(s)\n"
    "end=time.time()+float(sys.argv[1]);bad=[];wg=0\n"
    "while time.time()<end:\n"
    " for s in socks:\n"
    "  try: f,meta=s.recvfrom(2048)\n"
    "  except OSError: continue\n"
    "  if meta[2]==4: continue\n"
    "  t=struct.unpack('!H',f[12:14])[0]\n"
    "  if t==0x0806: continue\n"
    "  if t==0x86dd:\n"
    "   if f[20]==58 and f[54] in (133,134,135,136): continue\n"
    "   bad.append('ipv6 '+f[54:55].hex()+' nh'+str(f[20]));continue\n"
    "  if t!=0x0800: bad.append(hex(t));continue\n"
    "  ihl=(f[14]&15)*4;proto=f[23];src=socket.inet_ntoa(f[26:30])\n"
    "  if proto==17:\n"
    "   sp,dp=struct.unpack('!HH',f[14+ihl:18+ihl])\n"
    "   if 51820 in (sp,dp): wg+=1;continue\n"
    "  bad.append('proto%d %s->%s'%(proto,src,socket.inet_ntoa(f[30:34])))\n"
    "print(len(bad),'wg=%d'%wg,*bad[:5])\n"
)


def leak_matrix(lab):
    """Capture both underlay veths while the client sends DNS/DoT/QUIC/mDNS/NetBIOS/ICMP
    to underlay and public-looking destinations. Only WireGuard to the endpoint may appear."""
    sniff = subprocess.Popen(
        ["python3", "-c", SNIFFER, "6", "srv-client", "srv-client2"],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
    )
    time.sleep(1)
    lab.client_namespace.run(
        "python3", "-c", LEAK_SENDER, "192.0.2.1", "192.0.2.5", "8.8.8.8", "1.1.1.1", "198.51.100.2",
        check=False,
    )
    out, err = sniff.communicate(timeout=20)
    require(sniff.returncode == 0 and out.startswith("0 wg=") and not out.startswith("0 wg=0"),
            f"leak matrix: no non-WireGuard packet on the underlay (saw: {out.strip()} {err.strip()})")


def preexisting_tcp_check(lab):
    ready = os.path.join(lab.root, "tcp-ready")
    go = os.path.join(lab.root, "tcp-go")
    result = os.path.join(lab.root, "tcp-result")
    code = (
        "import os,socket,sys,time;"
        "s=socket.socket();s.settimeout(2);"
        "\nwhile True:\n"
        " try: s.connect(('192.0.2.1',9998)); break\n"
        " except OSError: time.sleep(.05)\n"
        "s.sendall(b'before');assert s.recv(64)==b'before';"
        "open(sys.argv[1],'w').close();\n"
        "while not os.path.exists(sys.argv[2]): time.sleep(.02)\n"
        "s.settimeout(1)\n"
        "try:\n s.sendall(b'after');s.recv(64);open(sys.argv[3],'w').write('leaked')\n"
        "except Exception:\n open(sys.argv[3],'w').write('blocked')"
    )
    process = subprocess.Popen(
        [
            "nsenter", "-t", str(lab.client_namespace.process.pid), "-n", "--",
            "python3", "-c", code, ready, go, result,
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    lab.helpers.append(process)
    def ready_or_failed():
        if os.path.exists(ready):
            return True
        if process.poll() is not None:
            error = process.stderr.read().decode(errors="replace")
            raise AssertionError(f"pre-existing TCP client failed: {error}")
        return False
    wait_for(ready_or_failed, "pre-existing TCP connection")
    return go, result, process


def make_topology(lab):
    run("ip", "link", "set", "lo", "up")

    upstream = lab.new_namespace()
    run("ip", "link", "add", "eth0", "type", "veth", "peer", "name", "up0")
    run("ip", "link", "set", "up0", "netns", str(upstream.process.pid))
    run("ip", "addr", "add", "198.51.100.1/24", "dev", "eth0")
    run("ip", "link", "set", "eth0", "up")
    upstream.run("ip", "link", "set", "lo", "up")
    upstream.run("ip", "addr", "add", "198.51.100.2/24", "dev", "up0")
    upstream.run("ip", "link", "set", "up0", "up")
    lab.helpers.append(upstream.popen("python3", "-c", ECHO))

    client = lab.new_namespace()
    lab.client_namespace = client
    run("ip", "link", "add", "srv-client", "type", "veth", "peer", "name", "cli-client")
    run("ip", "link", "set", "cli-client", "netns", str(client.process.pid))
    run("ip", "addr", "add", "192.0.2.1/30", "dev", "srv-client")
    run("ip", "-6", "addr", "add", "2001:db8:1::1/64", "dev", "srv-client", "nodad")
    run("ip", "link", "set", "srv-client", "up")
    client.run("ip", "link", "set", "lo", "up")
    client.run("ip", "addr", "add", "192.0.2.2/30", "dev", "cli-client")
    client.run("ip", "-6", "addr", "add", "2001:db8:1::2/64", "dev", "cli-client", "nodad")
    client.run("ip", "link", "set", "cli-client", "up")
    client.run("ip", "route", "add", "default", "via", "192.0.2.1")
    run("ip", "link", "add", "srv-client2", "type", "veth", "peer", "name", "cli-client2")
    run("ip", "link", "set", "cli-client2", "netns", str(client.process.pid))
    run("ip", "addr", "add", "192.0.2.5/30", "dev", "srv-client2")
    run("ip", "link", "set", "srv-client2", "up")
    client.run("ip", "addr", "add", "192.0.2.6/30", "dev", "cli-client2")
    client.run("ip", "link", "set", "cli-client2", "up")
    # Keep a known cleartext echo path on the client veth.  The server-side daemon
    # never uses this path for VPN traffic, but it makes leak assertions non-vacuous.
    lab.helpers.append(
        subprocess.Popen(
            ["python3", "-c", ECHO],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    )
    lab.helpers.append(
        subprocess.Popen(
            ["python3", "-c", ECHO6],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    )
    lab.helpers.append(
        subprocess.Popen(
            ["python3", "-c", TCP_ECHO],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    )
    wait_for(lambda: probe(client, "192.0.2.1", attempts=1) == "192.0.2.2", "cleartext echo")
    require(
        probe(client, "192.0.2.1") == "192.0.2.2",
        "cleartext veth echo works before the VPN is connected",
    )
    require(
        probe6(client, "2001:db8:1::1") == "2001:db8:1::2",
        "cleartext IPv6 veth echo works before the VPN is connected",
    )
    baseline = {
        family: json.loads(client.run("ip", "-j", family, "rule", "show").stdout)
        for family in ("-4", "-6")
    }
    client.run("nft", "add", "table", "inet", "unrelated_sentinel")
    return baseline


def configure_server(lab):
    lab.server(
        "setup",
        "--write-state",
        "--endpoint",
        "192.0.2.1:51820",
        "--pool",
        "10.66.0.0/24",
        "--wan-interface",
        "eth0",
        "--dns",
        "10.66.0.1",
    )
    key_file = os.path.join(lab.root, "client.key")
    identity = run(
        lab.client_bin,
        "--json",
        "identity",
        "generate",
        "--key-file",
        key_file,
    )
    public_key = json.loads(identity.stdout)["public_key"]
    lab.server(
        "peer",
        "create",
        "--name",
        "client",
        "--public-key",
        public_key,
        "--confirm-public-key",
    )
    strict_profile = os.path.join(lab.root, "strict.toml")
    vpn_only_profile = os.path.join(lab.root, "vpn-only.toml")
    lab.server(
        "peer",
        "export",
        "client",
        "--kill-switch",
        "strict",
        "--output",
        strict_profile,
    )
    lab.server(
        "peer",
        "export",
        "client",
        "--kill-switch",
        "vpn-only",
        "--output",
        vpn_only_profile,
    )
    server_status = json.loads(lab.server("status", "--json").stdout)
    return key_file, public_key, server_status["server_public_key"], strict_profile, vpn_only_profile


def import_profiles(lab, key_file, public_key, server_public, strict_profile, vpn_only_profile):
    wrong = lab.client(
        "--json",
        "profile",
        "import",
        strict_profile,
        "--name",
        "strict",
        "--key-file",
        key_file,
        "--expect-server-key",
        public_key,
        check=False,
    )
    require(
        wrong.returncode != 0 and "profile.server-key-mismatch" in wrong.stderr,
        "client rejects a profile when the expected server key is wrong",
    )
    imported = lab.client(
        "--json",
        "profile",
        "import",
        strict_profile,
        "--name",
        "strict",
        "--key-file",
        key_file,
        "--expect-server-key",
        server_public,
    )
    require(imported.returncode == 0, "client imports the strict profile through the broker")
    imported = lab.client(
        "--json",
        "profile",
        "import",
        vpn_only_profile,
        "--name",
        "vpnonly",
        "--key-file",
        key_file,
        "--expect-server-key",
        server_public,
    )
    require(imported.returncode == 0, "client imports the vpn-only profile through the broker")


def status(lab):
    result, data = lab.client_json("status")
    require(
        result.returncode == 0 and data is not None and data.get("service") == "running",
        "client status is available through the broker",
    )
    return data


def unmanaged_status(lab):
    current = status(lab)
    require(
        current["state"] == "degraded" and current["reasons"] == ["dns-unmanaged"],
        "unmanaged DNS is reported as exactly dns-unmanaged",
    )
    require(
        current["handshake_age_secs"] is not None and current["rx_bytes"] > 0,
        "live status observes a real handshake and received tunnel traffic",
    )
    require(
        {item["name"]: item["status"] for item in current["checks"]}
        == {
            "interface": "ok",
            "handshake": "ok",
            "endpoint-route": "ok",
            "ipv4": "ok",
            "ipv6": "ok",
            "firewall": "ok",
            "dns": "fail",
        },
        "all non-DNS protection checks are observed OK",
    )


def normal_networking(lab, baseline):
    client = lab.client_namespace
    # The scenario deliberately roams to cli-client2 and leaves cli-client down.
    # Restore the original cleartext path before asserting post-release behavior;
    # this is test-topology cleanup, not a LoVPN operation.
    client.run("ip", "link", "set", "cli-client", "up")
    client.run(
        "ip", "route", "replace", "192.0.2.1/32",
        "dev", "cli-client",
    )
    client.run(
        "ip", "route", "replace", "default",
        "via", "192.0.2.1", "dev", "cli-client", "onlink",
    )
    require(
        client.run("ip", "link", "show", "lovpn0", check=False).returncode != 0,
        "disconnect/reset removes the owned tunnel interface",
    )
    require(
        client.run("nft", "list", "table", "inet", "lovpn_client", check=False).returncode != 0,
        "released protection removes the client firewall table",
    )
    require(
        "unrelated_sentinel" in client.run("nft", "list", "tables").stdout,
        "disconnect/reset preserves unrelated firewall tables",
    )
    require(
        all(
            json.loads(client.run("ip", "-j", family, "rule", "show").stdout) == rules
            for family, rules in baseline.items()
        ),
        "disconnect/reset restores the original IPv4 and IPv6 policy rules",
    )
    require(
        probe(client, "192.0.2.1") == "192.0.2.2",
        "normal cleartext networking works after release/reset",
    )


def connect(lab, profile):
    result = lab.client("--json", "connect", profile, check=False)
    require(result.returncode == 0, f"real client connects the {profile} profile")
    wait_for(lambda: probe(lab.client_namespace, "198.51.100.2") == "198.51.100.1",
             f"{profile} tunnel traffic")


def scenario(lab):
    require(
        os.readlink("/proc/self/ns/net") != lab.host_netns,
        "client gate runs outside the host network namespace",
    )
    baseline = make_topology(lab)
    key_file, public_key, server_public, strict_profile, vpn_only_profile = configure_server(lab)

    lab.start_server_broker()
    lab.server("apply")
    require(json.loads(lab.server("status", "--live", "--json").stdout)["host"]["in_sync"],
            "server is applied before the client connects")

    lab.start_client_broker()
    import_profiles(lab, key_file, public_key, server_public, strict_profile, vpn_only_profile)
    require(len(json.loads(lab.client("--json", "profile", "list").stdout)["profiles"]) == 2,
            "broker stores both imported public profiles")

    tcp_go, tcp_result, tcp_process = preexisting_tcp_check(lab)
    connect(lab, "strict")
    open(tcp_go, "w").close()
    tcp_process.wait(timeout=5)
    require(
        open(tcp_result).read() == "blocked",
        "a pre-existing TCP connection cannot bypass the client kill switch",
    )
    unmanaged_status(lab)
    require(probe(lab.client_namespace, "198.51.100.2") == "198.51.100.1",
            "real WireGuard reaches the upstream echo through server NAT")
    require(
        bound_probe(lab.client_namespace, "192.0.2.1", "cli-client")
        in {"timeout", "bind-denied", "blocked"},
        "SO_BINDTODEVICE on the uplink cannot bypass the client firewall",
    )
    require(
        probe6(lab.client_namespace, "2001:db8:1::1") == "timeout",
        "IPv6 underlay traffic is blocked while IPv6 payload is disabled",
    )
    leak_matrix(lab)

    route_to_client = lab.client_namespace.run(
        "ip", "route", "replace", "192.0.2.1/32",
        "via", "192.0.2.5", "dev", "cli-client2", "onlink", check=False
    )
    require(
        route_to_client.returncode == 0,
        f"alternate uplink route installed ({route_to_client.stderr.strip()})",
    )
    default_to_client = lab.client_namespace.run(
        "ip", "route", "replace", "default",
        "via", "192.0.2.5", "dev", "cli-client2", "onlink", check=False
    )
    require(
        default_to_client.returncode == 0,
        f"alternate uplink default installed ({default_to_client.stderr.strip()})",
    )
    lab.client_namespace.run("ip", "link", "set", "cli-client", "down")
    require(
        probe_within(lab.client_namespace, "198.51.100.2", 20) == "198.51.100.1",
        "switching the uplink preserves tunnel traffic without a leak",
    )
    switched = status(lab)
    require(
        switched["checks"] and next(c for c in switched["checks"] if c["name"] == "endpoint-route")["status"] == "ok",
        "endpoint route remains observed through the switched uplink",
    )

    # Delete only the client tunnel.  The engine's routing rules remain fail-closed while
    # the monitor recreates the owned interface; no packet may fall back to the veth.
    # Stop the daemon monitor while observing the fault, so the packet test cannot
    # race a repair.  Protection remains in the kernel and is never lowered.
    lab.client_broker.send_signal(signal.SIGSTOP)
    try:
        lab.client_namespace.run("ip", "link", "del", "lovpn0")
        require(
            lab.client_namespace.run(
                "ip", "-j", "route", "get", "198.51.100.2", check=False
            ).returncode
            != 0,
            "interface loss leaves fail-closed routing, not an uplink fallback",
        )
        require(
            probe(lab.client_namespace, "192.0.2.1", attempts=1) == "timeout",
            "interface loss blocks the independently verified cleartext path",
        )
        require(
            "lovpn-owned"
            in lab.client_namespace.run(
                "nft", "list", "table", "inet", "lovpn_client"
            ).stdout,
            "interface loss leaves the owned kill switch installed",
        )
    finally:
        lab.client_broker.send_signal(signal.SIGCONT)
    wait_for(
        lambda: lab.client_namespace.run("ip", "link", "show", "lovpn0", check=False).returncode == 0,
        "client monitor interface repair",
        seconds=8,
    )
    require(
        probe_within(lab.client_namespace, "198.51.100.2", 40) == "198.51.100.1",
        "client monitor repairs the interface and traffic recovers",
    )
    unmanaged_status(lab)

    # Kill the broker, remove the kernel interface while it is down, then restart it.  The
    # durable desired-state record makes startup restore protection before serving requests.
    lab.stop_client_broker(force=True)
    require(
        status_without_service(lab),
        "a crashed broker is no longer serving client requests",
    )
    require(
        probe(lab.client_namespace, "198.51.100.2") == "198.51.100.1",
        "broker crash leaves the existing tunnel working",
    )
    lab.client_namespace.run("ip", "link", "del", "lovpn0")
    require(
        probe(lab.client_namespace, "192.0.2.1", attempts=1) == "timeout",
        "broker crash plus interface loss cannot use the cleartext uplink",
    )
    lab.start_client_broker()
    wait_for(
        lambda: lab.client_namespace.run("ip", "link", "show", "lovpn0", check=False).returncode == 0,
        "client broker restart recovery",
        seconds=8,
    )
    require(
        probe_within(lab.client_namespace, "198.51.100.2", 40) == "198.51.100.1",
        "broker restart recovers the tunnel from its durable record",
    )
    unmanaged_status(lab)

    # Reboot-style loss: discard every client-side kernel object while retaining the
    # durable profile/session record, then let startup restore the deny policy and tunnel.
    lab.stop_client_broker(force=True)
    lab.client_namespace.run("ip", "link", "del", "lovpn0")
    lab.client_namespace.run("ip", "-4", "rule", "del", "priority", "9100", check=False)
    lab.client_namespace.run("ip", "-4", "rule", "del", "priority", "9101", check=False)
    lab.client_namespace.run("ip", "-6", "rule", "del", "priority", "9100", check=False)
    lab.client_namespace.run("ip", "route", "flush", "table", "19567")
    lab.client_namespace.run("nft", "delete", "table", "inet", "lovpn_client")
    lab.start_client_broker()
    require(
        "lovpn-owned" in lab.client_namespace.run(
            "nft", "list", "table", "inet", "lovpn_client"
        ).stdout,
        "reboot-style startup restores the kill switch before serving status",
    )
    require(
        probe_within(lab.client_namespace, "198.51.100.2", 40) == "198.51.100.1",
        "reboot-style client restart restores the tunnel and traffic",
    )
    unmanaged_status(lab)

    # Strict disconnect intentionally leaves the kill switch armed until released.
    result = lab.client("--json", "disconnect", check=False)
    require(result.returncode == 0, "strict disconnect succeeds")
    blocked = status(lab)
    require(blocked["state"] == "blocked" and blocked["kill_switch_armed"],
            "strict disconnect remains blocked with the kill switch armed")
    require(probe(lab.client_namespace, "192.0.2.1", attempts=1) == "timeout",
            "strict disconnect does not leak while blocked")
    result = lab.client("--json", "disconnect", "--release-kill-switch", check=False)
    require(result.returncode == 0, "strict kill switch release succeeds")
    released = status(lab)
    require(released["state"] == "disconnected" and not released["kill_switch_armed"],
            "released strict disconnect restores normal networking")
    normal_networking(lab, baseline)

    connect(lab, "vpnonly")
    result = lab.client("--json", "disconnect", check=False)
    require(result.returncode == 0, "vpn-only disconnect succeeds")
    vpn_only_disconnected = status(lab)
    require(
        vpn_only_disconnected["state"] == "disconnected"
        and not vpn_only_disconnected["kill_switch_armed"],
        "vpn-only disconnect removes protection and restores normal networking",
    )
    normal_networking(lab, baseline)
    result = lab.client("--json", "reset", check=False)
    require(result.returncode == 0, "client reset succeeds after vpn-only disconnect")
    reset = status(lab)
    require(
        reset["state"] == "disconnected"
        and reset["profile"] is None
        and not reset["kill_switch_armed"],
        "reset disconnects, releases protection and forgets the selected profile",
    )
    normal_networking(lab, baseline)


def status_without_service(lab):
    result, data = lab.client_json("status")
    return result.returncode == 0 and data is not None and data.get("service") == "not-running"


def main(host_netns, server_bin, client_bin, clientd_bin):
    require(
        os.readlink("/proc/self/ns/net") != host_netns,
        "client gate runs outside the host network namespace",
    )
    require(os.getpid() == 1, "client gate is PID 1 in a disposable PID namespace")
    mapping = open("/proc/self/uid_map").read().split()
    require(
        os.geteuid() == 0
        and len(mapping) == 3
        and mapping[0] == "0"
        and mapping[2] == "1",
        "client gate runs as mapped root in a disposable user namespace",
    )
    lab = Lab(host_netns, server_bin, client_bin, clientd_bin)
    try:
        scenario(lab)
    finally:
        lab.close()


if __name__ == "__main__":
    main(*sys.argv[1:5])
